---
apiVersion: v1
kind: Service

metadata:
  name: loki
  namespace: logging

  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: logging-backend
    app.kubernetes.io/part-of: uptime-kuma-platform
    environment: dev

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: logging-backend

  ports:
    - name: http
      port: 3100
      targetPort: http

    - name: grpc
      port: 9095
      targetPort: grpc
