---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: external-secrets
  namespace: monitoring

  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: external-secrets-monitor
    app.kubernetes.io/part-of: uptime-kuma-platform
    environment: dev
    managed-by: argocd

spec:
  namespaceSelector:
    matchNames:
      - external-secrets

  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: external-secrets-webhook
  namespace: monitoring

  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: external-secrets-webhook-monitor
    app.kubernetes.io/part-of: uptime-kuma-platform
    environment: dev
    managed-by: argocd

spec:
  namespaceSelector:
    matchNames:
      - external-secrets

  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets-webhook

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: external-secrets-cert-controller
  namespace: monitoring

  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: external-secrets-cert-controller-monitor
    app.kubernetes.io/part-of: uptime-kuma-platform
    environment: dev
    managed-by: argocd

spec:
  namespaceSelector:
    matchNames:
      - external-secrets

  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets-cert-controller

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s