---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: uptime-kuma
  namespace: monitoring

  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: uptime-kuma-monitor
    app.kubernetes.io/part-of: uptime-kuma-platform
    environment: dev
    managed-by: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  namespaceSelector:
    matchNames:
      - uptime-kuma

  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
      app.kubernetes.io/instance: uptime-kuma

  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s

      basicAuth:
        username:
          name: uptime-kuma-prometheus-credentials
          key: username

        password:
          name: uptime-kuma-prometheus-credentials
          key: password