apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 3.4.0

      helm:
        releaseName: aws-load-balancer-controller

        valueFiles:
          - $values/gitops/values/aws-load-balancer-controller/dev.yaml

    - repoURL: https://github.com/ofekpensso/uptime-kuma-platform.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PruneLast=true

  ignoreDifferences:
    - kind: Secret
      name: aws-load-balancer-tls
      namespace: kube-system
      jqPathExpressions:
        - .data

    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle