---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kube-prometheus-stack
  namespace: argocd

  labels:
    app.kubernetes.io/part-of: uptime-kuma-platform
    environment: dev

  annotations:
    argocd.argoproj.io/sync-wave: "20"

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "87.2.1"

      helm:
        releaseName: kube-prometheus-stack

        valueFiles:
          - $values/gitops/values/kube-prometheus-stack/dev.yaml

    - repoURL: https://github.com/ofekpensso/uptime-kuma-platform.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true

    retry:
      limit: 5

      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m