---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: uptime-kuma
  namespace: argocd

  labels:
    app.kubernetes.io/part-of: uptime-kuma-platform
    environment: dev

  annotations:
    argocd.argoproj.io/sync-wave: "10"

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: https://github.com/ofekpensso/uptime-kuma-app.git
      targetRevision: main
      path: helm/uptime-kuma

      helm:
        releaseName: uptime-kuma

        valueFiles:
          - $values/gitops/values/uptime-kuma/dev.yaml

    - repoURL: https://github.com/ofekpensso/uptime-kuma-platform.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 5

      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m