---
replicaCount: 1

image:
  repository: 478468080341.dkr.ecr.us-east-1.amazonaws.com/uptime-kuma
  tag: sha-c4f37b366abf887f1d5c83166ab9d502930e1fd8
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automountServiceAccountToken: false

podLabels:
  project: uptime-kuma
  environment: dev
  managed-by: argocd

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001

headlessService:
  enabled: true
  port: 3001

persistence:
  enabled: true
  existingClaim: ""
  storageClass: gp3
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  mountPath: /app/data

  retentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Retain

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: alb

  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: uptime-kuma-dev-alb

    alb.ingress.kubernetes.io/tags: >-
      Project=uptime-kuma,
      Environment=dev,
      Application=uptime-kuma,
      ManagedBy=aws-load-balancer-controller

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP

    alb.ingress.kubernetes.io/load-balancer-attributes: >-
      routing.http.preserve_host_header.enabled=true,
      idle_timeout.timeout_seconds=3600

    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200-399"

  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

  tls: []