---
replicaCount: 1

image:
  repository: 478468080341.dkr.ecr.us-east-1.amazonaws.com/uptime-kuma
  tag: sha-846f3d4b331d26a303474683d3f3a0c2383b0c41
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automountServiceAccountToken: false

podLabels:
  project: uptime-kuma
  environment: dev
  managed-by: argocd

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001
  extraLabels:
    monitoring: "enabled"

headlessService:
  enabled: true
  port: 3001

persistence:
  enabled: true
  existingClaim: ""
  storageClass: gp3
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  mountPath: /app/data

  retentionPolicy:
    enabled: true
    whenDeleted: Delete
    whenScaled: Retain

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: alb

  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: uptime-kuma-dev-alb

    alb.ingress.kubernetes.io/tags: >-
      Project=uptime-kuma,
      Environment=dev,
      Application=uptime-kuma,
      ManagedBy=aws-load-balancer-controller

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ip-address-type: ipv4

    alb.ingress.kubernetes.io/listen-ports: >-
      [{"HTTP":80},{"HTTPS":443}]

    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:us-east-1:478468080341:certificate/13257d51-4efd-4abf-8feb-61af5d56eeb6

    alb.ingress.kubernetes.io/ssl-redirect: "443"

    alb.ingress.kubernetes.io/ssl-policy: >-
      ELBSecurityPolicy-TLS13-1-2-2021-06

    alb.ingress.kubernetes.io/backend-protocol: HTTP

    alb.ingress.kubernetes.io/load-balancer-attributes: >-
      routing.http.preserve_host_header.enabled=true,
      idle_timeout.timeout_seconds=3600

    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200-399"

    external-dns.alpha.kubernetes.io/hostname: >-
      uptime.oag-status-page-devops.site

  hosts:
    - host: uptime.oag-status-page-devops.site
      paths:
        - path: /
          pathType: Prefix

  tls: []
