---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: aws-secrets-manager

  labels:
    project: uptime-kuma
    environment: dev
    managed-by: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1

  conditions:
    - namespaces:
        - uptime-kuma
        - monitoring
