---
installCRDs: true

replicaCount: 1

serviceAccount:
  create: true
  automount: true
  name: external-secrets

commonLabels:
  project: uptime-kuma
  environment: dev
  managed-by: argocd

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

serviceMonitor:
  enabled: false

metrics:
  service:
    enabled: true
    port: 8080

webhook:
  metrics:
    service:
      enabled: true
      port: 8080

certController:
  metrics:
    service:
      enabled: true
      port: 8080
