---
provider:
  name: aws

env:
  - name: AWS_DEFAULT_REGION
    value: us-east-1

sources:
  - ingress

policy: upsert-only

registry: txt
txtOwnerId: uptime-kuma-dev

domainFilters:
  - oag-status-page-devops.site

extraArgs:
  zone-id-filter: Z05372092J2CCRJPB2LUJ
  aws-zone-type: public

serviceAccount:
  create: true
  name: external-dns
  annotations: {}

replicaCount: 1

interval: 1m
triggerLoopOnEvent: true

logLevel: info
logFormat: json

commonLabels:
  project: uptime-kuma
  environment: dev
  managed-by: argocd

resources:
  requests:
    cpu: 25m
    memory: 64Mi

  limits:
    cpu: 150m
    memory: 128Mi

serviceMonitor:
  enabled: false
