{
 "title": "Uptime Kuma Overview",
 "tags": [
  "uptime-kuma",
  "dev"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime Kuma Target",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{namespace=\"uptime-kuma\",service=\"uptime-kuma\"})"
    }
   ]
  },
  {
   "title": "Monitors Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_status{namespace=\"uptime-kuma\"} == bool 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Monitors Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_status{namespace=\"uptime-kuma\"} == bool 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(monitor_response_time{namespace=\"uptime-kuma\"})"
    }
   ]
  },
  {
   "title": "Monitor Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "monitor_response_time{namespace=\"uptime-kuma\"}",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Monitor Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "monitor_status{namespace=\"uptime-kuma\"}",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  }
 ]
}